### ISSUE TITLE
Create an SL7 version

### ISSUE THREAD

**Issue by stefco** [stefco/geco_vm#80]
According to Keith, we are migrating site packages to SL7. This will include support for things like remote MEDM screens.
- [x] follow up with Keith to determine which packages to install #81 
- [ ] get SL7 booting and installing on geco_vm #82
- [ ] get site packages working #83
- [ ] get extra geco stuff working #84

**Comment by stefco** [comment]
Stand-alone SL7 CDS workstation install [here](https://cdswiki.ligo-la.caltech.edu/foswiki/bin/view/CDS/StandaloneOffsiteWorkstationInstallationSL7). This answers the question of what to install #81:

``` bash
yum install cds-workstation subversion redhat-lsb
```

**Comment by stefco** [comment]
**GECo Trello:** [Talk to keith about the VM and see if it is handy and if he has tips](https://trello.com/c/iphq15eN)

**Comment by stefco** [comment]
Hi Stefan,

The RemoteMEDM wiki page has a pointer to the RemoteEPICS page for
installation instructions.  This sends you to RemoteMEDMBuildFromSource
for instructions on building MEDM from source.

However, this is no longer needed for SL7.  If you install the
Standalone workstation using the link below, then you will only need to
download and run the 'medm_llo.sh' and 'medm_lho.sh' scripts.  The
version of MEDM that comes with the cds-workstation metapackage now
includes the patches described on the RemoteMEDMBuildFromSource page.

Hope this helps,

--Mike
…
